name: Flutter CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'

      - name: Install dependencies
        working-directory: Mobile Application
        run: flutter pub get

      - name: Run tests
        working-directory: Mobile Application
        run: flutter test

      - name: Build APK
        working-directory: Mobile Application
        run: flutter build apk --release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: Mobile Application/build/app/outputs/flutter-apk/app-release.apk
